---
# Copyright 2016, Rackspace US, Inc.
#
# (C) 2016 Michael Rice <michael.rice@rackspace.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install distro packages
  package:
    name: "{{ item }}"
    state: "{{ cloudkitty_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ cloudkitty_distro_packages }}"

- name: Install distro packages for testing
  package:
    name: "{{ item }}"
    state: "{{ cloudkitty_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ cloudkitty_test_distro_packages }}"
  when: install_test_packages|bool

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in cloudkitty_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: cloudkitty_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ cloudkitty_requires_pip_packages }}"
    state: "{{ cloudkitty_pip_package_state }}"
    extra_args: >-
      {{ cloudkitty_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Retrieve checksum for venv download
  uri:
    url: "{{ cloudkitty_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: cloudkitty_venv_checksum
  when: cloudkitty_venv_download | bool

- name: Attempt venv download
  get_url:
    url: "{{ cloudkitty_venv_download_url }}"
    dest: "/var/cache/{{ cloudkitty_venv_download_url | basename }}"
    checksum: "sha1:{{ cloudkitty_venv_checksum.content | trim }}"
  register: cloudkitty_get_venv
  when: cloudkitty_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ cloudkitty_bin | dirname }}"
    state: absent
  when: cloudkitty_get_venv | changed

- name: Create cloudkitty venv dir
  file:
    path: "{{ cloudkitty_bin | dirname }}"
    state: directory
    mode: "0755"
  register: cloudkitty_venv_dir
  when: cloudkitty_get_venv | changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ cloudkitty_venv_download_url | basename }}"
    dest: "{{ cloudkitty_bin | dirname }}"
    copy: "no"
  when: cloudkitty_get_venv | changed
  notify:
    - Restart cloudkitty services

- name: Install pip packages
  pip:
    name: "{{ cloudkitty_pip_packages }}"
    state: "{{ cloudkitty_pip_package_state }}"
    virtualenv: "{{ cloudkitty_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ cloudkitty_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: cloudkitty_get_venv | failed or cloudkitty_get_venv | skipped
  notify:
    - Restart cloudkitty services

- name: CentOS remove python from path first
  file:
    path:  "{{ cloudkitty_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
    - cloudkitty_get_venv | changed

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto --reinitialize {{ cloudkitty_bin | dirname }}
  when: cloudkitty_get_venv | changed

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: aodh
    option: venv_tag
    value: "{{ cloudkitty_venv_tag }}"
